### ISSUE TITLE
Fix bug: first-round values show incorrect values if not all votes were transferred

### ISSUE THREAD

**Issue by artoonie** [artoonie/rcvis#15]
Delivered.

Old: 
<img width="654" alt="old-data" src="https://user-images.githubusercontent.com/537316/61187876-43aee380-a645-11e9-9a9e-4ffd0d887767.png">

Fixed:
<img width="630" alt="new-data" src="https://user-images.githubusercontent.com/537316/61187884-67722980-a645-11e9-969f-3564f6cac368.png">

Notice that this bug led to several issues:
1. First-round incorrect totals
2. Incorrect totals for rounds after a winner had overvotes transferred away (C is correctly showing 7.25 votes instead of 8)
3. Incorrect total in the second-round caused by a combination of (1) and (2)

This was a bug only visible in multi-winner rounds with overflow votes getting redistributed, as visible here: http://rcvis.arminsamii.com/visualize=2019-02-04_22-51-06_summaryjson

**Comment by davidryal** [comment]
does this have to do with the need to separately display exhausted ballots?

**Comment by artoonie** [comment]
Yep - I handle exhausted votes in the middle of the diagram, just not on the first round.
