### ISSUE TITLE
slider on the Bar Graph to only show results up to a certain round

### ISSUE THREAD

**Issue by davidryal** [artoonie/rcvis#17]
It would look similar to how it is today, except instead of showing the most votes a candidate had, it would show how many votes they had on a certain round (meaning that it would show "0 [Eliminated]" for eliminated candidates, and wouldn't show results higher than Round X when the slider is on X. Thus, by paging through each round, the view can see how the election developed "frame by frame"

**Comment by artoonie** [comment]
Designed this to work the "normal" way, and while visualizing overvotes.

![Multi_winner2-Ranked-Choice-Voting-Visualization-Google-Chrome-2019-07-14-14-58-49_Trim_xQ4ysZ7E_m5s](https://user-images.githubusercontent.com/537316/61188113-80c8a500-a648-11e9-8e83-3f63e20836ce.gif)

Here's how the static equivalent looks:
<img width="588" alt="static" src="https://user-images.githubusercontent.com/537316/61188128-c4231380-a648-11e9-8022-6e7cf66e9fff.png">
