### ISSUE TITLE
slider on Tabular format which shows the results per-round

### ISSUE THREAD

**Issue by davidryal** [artoonie/rcvis#18]
Using a similar slider to the Bar graph option, create a new Tabular format which shows the results per-round, rather than the results per-candidate-per-round, so that it's similar to the CCD Round-by-Round results but they wouldn't live on their own page

**Comment by artoonie** [comment]
I began working on the per-round format and felt a slider didn't make too much sense given the small amount of data we want to show. We can consider adding extra columns (e.g. "Transfers"?).
It fits pretty easily on one page: http://rcvis.arminsamii.com/visualize=2017_minneapolis_mayorjson#tabular-by-round

See the image:
<img width="569" alt="roundbyround" src="https://user-images.githubusercontent.com/537316/60690493-bc6bae00-9e95-11e9-96b3-56af4d98a2db.png">

I updated the text to have "Summary by Candidate" and "Summary by Round" to clarify the difference.

What are your thoughts on this? Does this meet the goals of including a CCD round-by-round summary? If not:
- Would additional columns help, or if not,
- What data should change as we move the slider, beyond only showing one row at a time?

**Comment by davidryal** [comment]
I think the idea is to show the same data (and at least to start, structure) as the tabular format from the Minneapolis version: http://vote.minneapolismn.gov/results/2017/2017-mayor-tabulation

Basically, instead of vertically stacking the data from each round like that version does, we would page those in a single box the way the bar graph above it does on that same page. As it pages, the names remain in the same place, but the round title changes, and the vote totals (+/-) change throughout the rounds. Basically, just a round-by-round "flipbook" -- does that make sense? (I missed multiple opportunities to explain previously that we probably want to draw more from the MN version for this than the CCD tabular results -- lazy on my part, sorry)

**Comment by davidryal** [comment]
this seems done to me, no?

**Comment by artoonie** [comment]
Yep! It's in Delivered - I think I was leaving it up to you to verify the Completion status in case stakeholders have additional comments or requests

**Comment by davidryal** [comment]
ha, somehow i commented on this from a non-kanban view of the task and didn't notice 😅 seems complete to me; other tweaks can use new issues 👍
