### ISSUE TITLE
Both bar charts: There should be marks noting when a candidate wins or is eliminated.

### ISSUE THREAD

**Issue by artoonie** [artoonie/rcvis#20]

**Comment by davidryal** [comment]
@artoonie i like the red X's -- maybe also a green checkmark next to the winner(s)? (yes 631 is more than 577, so not really necessary but an idea.)

**Comment by artoonie** [comment]
Can you send an example? I _think_ you may have been on one of the results with the Global Option set to ignore the final winner - thus, intentionally, the lack of green checkmark?
