### ISSUE TITLE
Add percentages to text wherever number of votes is listed

### ISSUE THREAD

**Issue by artoonie** [artoonie/rcvis#23]
Done for the graphical representations, not the tabular. If we want it for tabular, can we create another story? (In short, the graphs can be done with a shared JS module, the tabular formats need a shared Python module - just the way I happened to architect it)

**Comment by davidryal** [comment]
also mentioned by eastpointe folks, right? probably worth doing

**Comment by davidryal** [comment]
@artoonie it doesn't look like this happens for 'round-by-round' or 'candidate summary' -- but looks great on the bars and sankey!

**Comment by artoonie** [comment]
Uh, somehow I edited the comment above instead of leaving a new comment. It's dated July 21st, but I wrote it today :)

See above for the answer! The tabular format is an HTML table generated with django/python and no javascript, whereas the graphs are D3 elements mostly done with Javascript. Not justifying the disparity, just explaining further :)

**Comment by davidryal** [comment]
ha, i missed that. closing this.
