### ISSUE TITLE
Installation requirements

### ISSUE THREAD

**Issue by iankevinmcdonald** [artoonie/rcvis#442]
I figured I should post what I needed to install to get it working, in case it's worth including in docs.

Installing on WSL Ubuntu, I'm finding another couple of things I need to make sure are there, in addition to the two you mention.
* curl-config
* pg_config

I suspect that source compilation is not the only way to finish "Building wheel for pycurl", but it was the first route suggested, so I took it. I had to install these packages.
* gcc
* libcurl4-openssl-dev
* libcurl4-gnutls28-dev
* libpq-dev
* python3-dev

**Comment by artoonie** [comment]
Closing out some old issues. If needed, we can revisit adding this to the README, or to a WSL-specific installation script.
