### ISSUE TITLE
timeline-range-slider/slider.css' could not be found in the COMPRESS_ROOT

### ISSUE THREAD

**Issue by jameshowison** [artoonie/rcvis#453]
Exciting stuff :)

I'm trying to get this to build as a Docker image (I'm afraid I run into virtualenv issues build on my host OS, and I'm hoping to document using rcvis without installing anything other than Docker Desktop).  So I'm hoping to use repo2docker: https://github.com/jupyterhub/repo2docker. In short repo2docker tries to use files like requirements.txt to build a docker image with all the code and dependencies.

I ran into one issue with confusion between a distutils pycurl and the pycurl in the ./infra/requirements-not-for-readthedocs.txt file, which removing the pinned pycurl seemed to work (ie that file now just lists `pycurl` without the version number.

I was then able to get the docker image to build and run.   I then attempted to run the ./scripts/serve.sh script, realized I needed a `.env` file (which I added to the repo folder, then rebuilt).

Running the ./scripts/serve.sh script I'm seeing this error:

```bash
./scripts/serve.sh 
Cleared cache
Compressing... CommandError: An error occurred during rendering /home/jlh5498/templates/visualizer/common-visualizer-nonblocking.html: '%40artoonie/timeline-range-slider/timeline-range-slider/slider.css' could not be found in the COMPRESS_ROOT '/home/jlh5498/static' or with staticfiles.
```

Seems to be something Django related :) Any ideas?

Thanks,
James

**Comment by artoonie** [comment]
Sorry for the very late reply, just now seeing this!

The README instructions should be updated with how to fix this: you also need to run `npm install` to get the timeline-range-slider installed.
